# Consolidated workflow to build and test Go, Java, and C# solutions
name: Build and Test LeetCode Solutions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-go:
    name: Build and Test Go Solutions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build
      working-directory: ./golang
      run: go build -v ./...
    - name: Test
      working-directory: ./golang
      run: go test -v ./...

  build-java:
    name: Build and Test Java Solutions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file java/pom.xml
    - name: Test with Maven
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test --file java/pom.xml
      
  build-csharp:
    name: Build and Test C# Solutions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore csharp/
    - name: Build
      run: dotnet build --no-restore csharp/
    - name: Test
      run: dotnet test --no-build --verbosity normal csharp/
